language: go
go:
- 1.7.x
- 1.8.x
- 1.9.x
install:
- go get -u honnef.co/go/tools/cmd/megacheck
- go get -u github.com/client9/misspell/cmd/misspell
- go get -u github.com/nats-io/go-nats
- go get -u github.com/nats-io/gnatsd
- go get -u github.com/hashicorp/raft
- go get -u github.com/hashicorp/raft-boltdb
before_script:
- go build
- $(exit $(go fmt ./... | wc -l))
- go vet ./...
- misspell -error -locale US .
- megacheck ./...
script:
- go test -i -race .
